// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"


open Ast


# 12 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | IDENT of (System.String)
  | SINGLEQOUTE
  | EQUALS
  | RBRACKET
  | LBRACKET
  | EOF
  | STAR
  | HASH
  | DOT
  | COMMA
  | GREATER
  | PLUS
  | S
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_IDENT
    | TOKEN_SINGLEQOUTE
    | TOKEN_EQUALS
    | TOKEN_RBRACKET
    | TOKEN_LBRACKET
    | TOKEN_EOF
    | TOKEN_STAR
    | TOKEN_HASH
    | TOKEN_DOT
    | TOKEN_COMMA
    | TOKEN_GREATER
    | TOKEN_PLUS
    | TOKEN_S
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_Init
    | NONTERM_SelectorsGroup
    | NONTERM_Selector
    | NONTERM_FullSimpleSelectorSeq
    | NONTERM_SimpleSelectorSeq
    | NONTERM_SimpleSelector
    | NONTERM_AttributeValue
    | NONTERM_AttributeComparison
    | NONTERM_Combinator

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | IDENT _ -> 0 
  | SINGLEQOUTE  -> 1 
  | EQUALS  -> 2 
  | RBRACKET  -> 3 
  | LBRACKET  -> 4 
  | EOF  -> 5 
  | STAR  -> 6 
  | HASH  -> 7 
  | DOT  -> 8 
  | COMMA  -> 9 
  | GREATER  -> 10 
  | PLUS  -> 11 
  | S  -> 12 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_IDENT 
  | 1 -> TOKEN_SINGLEQOUTE 
  | 2 -> TOKEN_EQUALS 
  | 3 -> TOKEN_RBRACKET 
  | 4 -> TOKEN_LBRACKET 
  | 5 -> TOKEN_EOF 
  | 6 -> TOKEN_STAR 
  | 7 -> TOKEN_HASH 
  | 8 -> TOKEN_DOT 
  | 9 -> TOKEN_COMMA 
  | 10 -> TOKEN_GREATER 
  | 11 -> TOKEN_PLUS 
  | 12 -> TOKEN_S 
  | 15 -> TOKEN_end_of_input
  | 13 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_Init 
    | 3 -> NONTERM_SelectorsGroup 
    | 4 -> NONTERM_SelectorsGroup 
    | 5 -> NONTERM_Selector 
    | 6 -> NONTERM_Selector 
    | 7 -> NONTERM_FullSimpleSelectorSeq 
    | 8 -> NONTERM_SimpleSelectorSeq 
    | 9 -> NONTERM_SimpleSelectorSeq 
    | 10 -> NONTERM_SimpleSelector 
    | 11 -> NONTERM_SimpleSelector 
    | 12 -> NONTERM_SimpleSelector 
    | 13 -> NONTERM_SimpleSelector 
    | 14 -> NONTERM_SimpleSelector 
    | 15 -> NONTERM_SimpleSelector 
    | 16 -> NONTERM_AttributeValue 
    | 17 -> NONTERM_AttributeComparison 
    | 18 -> NONTERM_Combinator 
    | 19 -> NONTERM_Combinator 
    | 20 -> NONTERM_Combinator 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 15 
let _fsyacc_tagOfErrorTerminal = 13

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | IDENT _ -> "IDENT" 
  | SINGLEQOUTE  -> "SINGLEQOUTE" 
  | EQUALS  -> "EQUALS" 
  | RBRACKET  -> "RBRACKET" 
  | LBRACKET  -> "LBRACKET" 
  | EOF  -> "EOF" 
  | STAR  -> "STAR" 
  | HASH  -> "HASH" 
  | DOT  -> "DOT" 
  | COMMA  -> "COMMA" 
  | GREATER  -> "GREATER" 
  | PLUS  -> "PLUS" 
  | S  -> "S" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | IDENT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | SINGLEQOUTE  -> (null : System.Object) 
  | EQUALS  -> (null : System.Object) 
  | RBRACKET  -> (null : System.Object) 
  | LBRACKET  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
  | STAR  -> (null : System.Object) 
  | HASH  -> (null : System.Object) 
  | DOT  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | GREATER  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | S  -> (null : System.Object) 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 1us; 65535us; 0us; 3us; 3us; 65535us; 0us; 5us; 6us; 7us; 9us; 10us; 3us; 65535us; 0us; 8us; 6us; 8us; 9us; 8us; 3us; 65535us; 0us; 11us; 6us; 11us; 9us; 11us; 4us; 65535us; 0us; 12us; 6us; 12us; 9us; 12us; 11us; 13us; 1us; 65535us; 23us; 24us; 1us; 65535us; 21us; 23us; 1us; 65535us; 8us; 9us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 7us; 11us; 15us; 19us; 24us; 26us; 28us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 2us; 2us; 4us; 1us; 2us; 1us; 3us; 1us; 4us; 1us; 4us; 2us; 5us; 6us; 1us; 6us; 1us; 6us; 2us; 7us; 9us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 11us; 1us; 12us; 1us; 12us; 1us; 13us; 1us; 13us; 2us; 14us; 15us; 2us; 14us; 15us; 1us; 14us; 1us; 15us; 1us; 15us; 1us; 15us; 1us; 16us; 1us; 16us; 1us; 16us; 1us; 17us; 1us; 18us; 1us; 19us; 1us; 20us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 9us; 11us; 13us; 15us; 17us; 20us; 22us; 24us; 27us; 29us; 31us; 33us; 35us; 37us; 39us; 41us; 43us; 46us; 49us; 51us; 53us; 55us; 57us; 59us; 61us; 63us; 65us; 67us; 69us; |]
let _fsyacc_action_rows = 33
let _fsyacc_actionTableElements = [|5us; 32768us; 0us; 15us; 4us; 20us; 6us; 14us; 7us; 18us; 8us; 16us; 0us; 49152us; 0us; 16385us; 2us; 32768us; 5us; 4us; 9us; 6us; 0us; 16386us; 0us; 16387us; 5us; 32768us; 0us; 15us; 4us; 20us; 6us; 14us; 7us; 18us; 8us; 16us; 0us; 16388us; 3us; 16389us; 10us; 30us; 11us; 32us; 12us; 31us; 5us; 32768us; 0us; 15us; 4us; 20us; 6us; 14us; 7us; 18us; 8us; 16us; 0us; 16390us; 5us; 16391us; 0us; 15us; 4us; 20us; 6us; 14us; 7us; 18us; 8us; 16us; 0us; 16392us; 0us; 16393us; 0us; 16394us; 0us; 16395us; 1us; 32768us; 0us; 17us; 0us; 16396us; 1us; 32768us; 0us; 19us; 0us; 16397us; 1us; 32768us; 0us; 21us; 2us; 32768us; 2us; 29us; 3us; 22us; 0us; 16398us; 1us; 32768us; 1us; 26us; 1us; 32768us; 3us; 25us; 0us; 16399us; 1us; 32768us; 0us; 27us; 1us; 32768us; 1us; 28us; 0us; 16400us; 0us; 16401us; 0us; 16402us; 0us; 16403us; 0us; 16404us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 6us; 7us; 8us; 11us; 12us; 13us; 19us; 20us; 24us; 30us; 31us; 37us; 38us; 39us; 40us; 41us; 43us; 44us; 46us; 47us; 49us; 52us; 53us; 55us; 57us; 58us; 60us; 62us; 63us; 64us; 65us; 66us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 2us; 1us; 3us; 1us; 3us; 1us; 1us; 2us; 1us; 1us; 2us; 2us; 3us; 5us; 3us; 1us; 1us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 3us; 3us; 4us; 4us; 5us; 6us; 6us; 7us; 7us; 7us; 7us; 7us; 7us; 8us; 9us; 10us; 10us; 10us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 16385us; 65535us; 16386us; 16387us; 65535us; 16388us; 65535us; 65535us; 16390us; 65535us; 16392us; 16393us; 16394us; 16395us; 65535us; 16396us; 65535us; 16397us; 65535us; 65535us; 16398us; 65535us; 65535us; 16399us; 65535us; 65535us; 16400us; 16401us; 16402us; 16403us; 16404us; |]
let _fsyacc_reductions ()  =    [| 
# 169 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  Ast.selectorsGroup )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 178 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Init)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                          _1 
                   )
# 51 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 :  Ast.selectorsGroup ));
# 189 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SelectorsGroup)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                                   Ast.SelectorsGroup (List.rev _1) 
                   )
# 53 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'Init));
# 200 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Selector)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                         [_1] 
                   )
# 57 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'SelectorsGroup));
# 211 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SelectorsGroup)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'Selector)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 58 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                                         _3 :: _1 
                   )
# 58 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'SelectorsGroup));
# 223 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'FullSimpleSelectorSeq)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                                        Ast.Selector _1 
                   )
# 61 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'Selector));
# 234 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'FullSimpleSelectorSeq)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Combinator)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'Selector)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 62 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                                                       Ast.SelectorSequence (_1, _2, _3) 
                   )
# 62 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'Selector));
# 247 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleSelectorSeq)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 64 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                                                Ast.SimpleSelectorSeq (List.rev _1) 
                   )
# 64 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'FullSimpleSelectorSeq));
# 258 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleSelector)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 67 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                              [_1] 
                   )
# 67 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'SimpleSelectorSeq));
# 269 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleSelectorSeq)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleSelector)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 68 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                                            _2 :: _1 
                   )
# 68 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'SimpleSelectorSeq));
# 281 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 71 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                  Ast.Global 
                   )
# 71 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'SimpleSelector));
# 291 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : System.String)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 72 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                   Ast.Tag(_1) 
                   )
# 72 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'SimpleSelector));
# 302 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : System.String)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 73 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                      Ast.Class(_2) 
                   )
# 73 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'SimpleSelector));
# 313 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : System.String)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 74 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                      Ast.Id(_2) 
                   )
# 74 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'SimpleSelector));
# 324 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : System.String)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 75 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                                  Ast.Attribute(_2) 
                   )
# 75 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'SimpleSelector));
# 335 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : System.String)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'AttributeComparison)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'AttributeValue)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 76 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                                                                     Ast.AttributeComparsion (_2, _3, _4) 
                   )
# 76 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'SimpleSelector));
# 348 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : System.String)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 79 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                                        _2 
                   )
# 79 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'AttributeValue));
# 359 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 82 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                   Ast.Equals 
                   )
# 82 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'AttributeComparison));
# 369 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 85 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                    Ast.Child 
                   )
# 85 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'Combinator));
# 379 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 86 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                Ast.Descendant 
                   )
# 86 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'Combinator));
# 389 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 87 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                                  Ast.Sibling 
                   )
# 87 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fsy"
                 : 'Combinator));
|]
# 400 "F:\Workspace\F#Fuckabout\HtmlAgilityCssSelectors\Parser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 16;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf :  Ast.selectorsGroup  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
